dist: xenial
language: python
cache: pip
notifications:
  email: false
python:
- '3.8'
- '3.7'
- '3.6'
install:
- pip install -r dev-requirements.txt
script:
- pytest
stages:
- lint
- test
- deploy
jobs:
  include:
  - stage: lint
    install:
    - pip install black
    script:
    - black --check fhir_parse_qs tests
  - stage: deploy
    deploy:
    - provider: pypi
      user: __token__
      password:
        secure: Hxub0BddMqZxWhze0nBBfjTP8X5NCpUmMW0sPp+AI+l+CVo12M8myKGnQDcMpxbThlKKsU8cVIVkh9GJc/MCw3Wme3+2lZITAmdfvwAnaIpPCnaZiipNe0EQMsb0hFcDy0KMC6+TgSBmvd1VY4lMPqrif8+Ixzfq7F52duxylGWSu1R5UxlvyPlwgQJO+e0qltkSWA8YJ1LZtcYe/Uwy+aumCMDeWyL7JWERpqy1aLQ/77x/Qn3gMdJZCVyE3fliriWWQR4joeDxwxpBTuqvwQAxNiq3XX4xhw5vXB33gIqyi5qcBrVtX1BOTNnECxg0BbFXk4lfQF7gbvrXIAyyaOY1/ef4rdg+qdSQH9LV+aMX+WtjRQDN7TDjcSucZwL2m296IMq5/O1RsxJ3rtsAtqv/pwDfMymTjA7hdesgZQEZt3RwPjawgh9DJHP4mORY/xuWZnA0GVEGyWmPLyfnQcc6uVBNCBhxH2Kq/O7/aHYZzgSo3N9DcssE23uRkVKoNQlQll9tSrJ6jg1d9F+951y9Xa8gReje697wRa3h2csL8KotGgqwIfcPfnsiXI8uw3+wgNVJ8mWumKKZdWF1Y37tFVYGYPISyspFDyYTfcJwdlb9hfRqXzY2wkQyPQLDnj1wT0kZlZT6kr0vIxT3aaaLziEYG69H7P3UiZyuJNU=
      distributions: sdist bdist_wheel
      skip_cleanup: true
      skip_existing: true
      on:
        repo: teffalump/fhir_parse_qs
        branch: master
        tags: true
        python: '3.8'
