dist: xenial
language: python
cache: pip
notifications:
  email: false
python:
- '3.8'
- '3.7'
- '3.6'
install:
- pip install -r dev-requirements.txt
script:
- pytest
stages:
- lint
- test
- deploy
jobs:
  include:
  - stage: lint
    install:
    - pip install black
    script:
    - black --check fhir_parse_qs tests
  - stage: deploy
    deploy:
    - provider: pypi
      user: __token__
      password:
        secure: IUv/oymAycEkTs3ehnWMuOynP4stu+HdlFGfh5msPgMQ89lZgCHsk0u9t7Xa5Fv70LSuzk8I0DSqjnUd/+VhyA3LPpxtlm1XQSV8U7F5e6BCYHcmykhQQkHLhBq9t8dnfrG0W2vko0zvTUeOayB6Eo8lz54apEkElGMUr47pEHWxEgDbJHam73Ga5UJ1B5pr/hWdHOFEQNsVvq5/UxQbg9rkcX824J7Iu4j9JLSNmHes3YPO1S6/tVgI+5Gr8p3rp/QqDoOOrQxTUJ5vndidvAokWp3NoTCzdvnKjMuV2myk7IhrDszq6jg5/rMJKqxNejjZwqgBlE0UkH6Te0nxILd5jyJp72GkDi7aVR1hzQvGS/3pu0cGgB3682av31xGkqD/xu8++hnIBdkcAaid2s94Qe7sgQE3rhnGbR43l8lQHnsM+kyGawyGetYCB4oay4gDszFUrQ/PMbll7LMe8K0YIrHFdc04MCt0hRJSObEDhejBjklBCNESiGSS3x9ectzGw7MHTiCm9BkYBxqGoNxjFbcwPq2c+RqgA6Lok/ggJ8gKQYuEpQ1moluebxkYSX+3eSNHt92Gp95GCqhRwte0NBKAeavm6uwR9oJH8x/n28wXQPWnRMecVyU5cIfS/Lf45ompMAhpWsUJ6uuiRv1eNtmc7OF0V1n5gtgbczM=
      distributions: sdist bdist_wheel
      skip_cleanup: true
      skip_existing: true
      on:
        repo: teffalump/fhir_parse_qs
        branch: master
        tags: true
        python: '3.8'
