mapping = {
        'appointment':  'reference',
        'class':  'token',
        'date':  'date',
        'diagnosis':  'reference',
        'episodeofcare':  'reference',
        'identifier':  'token',
        'incomingreferral':  'reference',
        'length':  'number',
        'location':  'reference',
        'location-period':  'date',
        'part-of':  'reference',
        'participant':  'reference',
        'participant-type':  'token',
        'patient':  'reference',
        'practitioner':  'reference',
        'reason':  'token',
        'service-provider':  'reference',
        'special-arrangement':  'token',
        'status':  'token',
        'subject':  'reference',
        'type':  'token',
        }

references = {
        'appointment': ['Appointment'],
        'diagnosis': ['Condition', 'Procedure'],
        'episodeofcare': ['EpisodeOfCare'],
        'incomingreferral': ['ReferralRequest'],
        'location': ['Location'],
        'part-of': ['Encounter'],
        'participant': ['Practitioner', 'RelatedPerson'],
        'patient': ['Patient'],
        'practitioner': ['Practitioner'],
        'service-provider': ['Organization'],
        'subject': ['Group', 'Patient'],
        }

