mapping = {
        'based-on':  'reference',
        'category':  'token',
        'code':  'token',
        'context':  'reference',
        'date':  'date',
        'diagnosis':  'token',
        'encounter':  'reference',
        'identifier':  'token',
        'image':  'reference',
        'issued':  'date',
        'patient':  'reference',
        'performer':  'reference',
        'result':  'reference',
        'specimen':  'reference',
        'status':  'token',
        'subject':  'reference',
        }

references = {
        'based-on': ['ReferralRequest', 'CarePlan', 'MedicationRequest', 'NutritionOrder', 'ProcedureRequest', 'ImmunizationRecommendation'],
        'context': ['EpisodeOfCare', 'Encounter'],
        'encounter': ['Encounter'],
        'image': ['Media'],
        'patient': ['Patient'],
        'performer': ['Practitioner', 'Organization'],
        'result': ['Observation'],
        'specimen': ['Specimen'],
        'subject': ['Group', 'Device', 'Patient', 'Location'],
        }
