mapping = {
        'activity-code': 'token',
        'activity-date': 'date',
        'activity-reference': 'reference',
        'based-on': 'reference',
        'care-team': 'reference',
        'category': 'token',
        'condition': 'reference',
        'context': 'reference',
        'date': 'date',
        'definition': 'reference',
        'encounter': 'reference',
        'goal': 'reference',
        'identifier': 'token',
        'intent': 'token',
        'part-of': 'reference',
        'patient': 'reference',
        'performer': 'reference',
        'replaces': 'reference',
        'status': 'token',
        'subject': 'reference',
        }

references = {
        'activity-reference': ['Appointment', 'ReferralRequest', 'MedicationRequest', 'Task',
                                'NutritionOrder', 'RequestGroup', 'VisionPrescription', 'ProcedureRequest',
                                'DeviceRequest', 'CommunicationRequest'],
        'based-on': ['CarePlan'],
        'care-team': ['CareTeam'],
        'condition': ['Condition'],
        'context': ['EpisodeOfCare', 'Encounter'],
        'definition': ['Questionnaire', 'PlanDefinition'],
        'encounter': ['Encounter'],
        'goal': ['Goal'],
        'part-of': ['CarePlan'],
        'patient': ['Patient'],
        'performer': ['Practitioner', 'Organization', 'CareTeam', 'Patient', 'RelatedPerson'],
        'replaces': ['CarePlan'],
        'subject': ['Group', 'Patient'],
        }
