mapping = {
    'abatement-age': 'quantity',
    'abatement-boolean': 'token',
    'abatement-date': 'date',
    'abatement-string': 'string',
    'asserted-date': 'date',
    'asserter': 'reference',
    'body-site': 'token',
    'category': 'token',
    'clinical-status': 'token',
    'code': 'token',
    'context': 'reference',
    'encounter': 'reference',
    'evidence': 'token',
    'evidence-detail': 'reference',
    'identifier': 'token',
    'onset-age': 'quantity',
    'onset-date': 'date',
    'onset-info': 'string',
    'patient': 'reference',
    'severity': 'token',
    'stage': 'token',
    'subject': 'reference',
    'verification-status': 'token',
    }
