mapping = {
    'active': 'token',
    'address': 'string',
    'address-city': 'string',
    'address-country': 'string',
    'address-postalcode': 'string',
    'address-state': 'string',
    'address-use': 'token',
    'animal-breed': 'token',
    'animal-species': 'token',
    'birthdate': 'date',
    'death-date': 'date',
    'deceased': 'token',
    'email': 'token',
    'family': 'string',
    'gender': 'token',
    'general-practitioner': 'reference',
    'given': 'string',
    'identifier': 'token',
    'language': 'token',
    'link': 'reference',
    'name': 'string',
    'organization': 'reference',
    'phone': 'token',
    'phonetic': 'string',
    'telecom': 'token',
    }
