mapping = {
        'active':  'token',
        'address':  'string',
        'address-city':  'string',
        'address-country':  'string',
        'address-postalcode':  'string',
        'address-state':  'string',
        'address-use':  'token',
        'communication':  'token',
        'email':  'token',
        'family':  'string',
        'gender':  'token',
        'given':  'string',
        'identifier':  'token',
        'name':  'string',
        'phone':  'token',
        'phonetic':  'string',
        'telecom':  'token',
        }
