mapping = {
        'based-on': 'reference',
        'category': 'token',
        'code': 'token',
        'context':  'reference',
        'date':  'date',
        'definition': 'reference',
        'encounter': 'reference',
        'identifier': 'token',
        'location': 'reference',
        'part-of': 'reference',
        'patient': 'reference',
        'performer': 'reference',
        'status': 'token',
        'subject': 'reference',
        }
