mapping = {
        'authored':  'date',
        'based-on':  'reference',
        'body-site':  'token',
        'code':  'token',
        'context':  'reference',
        'definition':  'reference',
        'encounter':  'reference',
        'identifier':  'token',
        'intent':  'token',
        'occurrence':  'date',
        'patient':  'reference',
        'performer':  'reference',
        'performer-type':  'token',
        'priority':  'token',
        'replaces':  'reference',
        'requester':  'reference',
        'requisition':  'token',
        'specimen':  'reference',
        'status':  'token',
        'subject':  'reference',
        }
